<?if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true)die();?>
<?
$aMenuLinks = Array(
	Array(
		"Услуги",
		"services/",
		Array(), 
		Array(), 
		"" 
	),
    Array(
        "Наши работы",
        "works/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Преимущества",
        "works/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Блог",
        "blog/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Контакты",
        "contacts/",
        Array(),
        Array(),
        ""
    ),
);
?>